SYNCQT.HEADER_FILES = ../../include/QtUCL/qtucl.h ../../include/QtUCL/ucl
SYNCQT.HEADER_CLASSES = ../../include/QtUCL/QtUCL
SYNCQT.PRIVATE_HEADER_FILES =
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.INJECTIONS = 
